version: 1.2
workflows:

   -  name: single-descriptor-with-input
      subclass: WDL
      primaryDescriptorPath: workflows/wdl/w1/singleDescriptorWithInput.wdl
      testParameterFiles:
        - /workflows/wdl/w1/test.json
        
   -  name: multi-descriptor-no-input
      subclass: WDL
      primaryDescriptorPath: workflows/wdl/w2/multiDescriptorNoInput.wdl
