version: 1.2
workflows:

   -  name: single-descriptor-with-input
      subclass: WDL
      primaryDescriptorPath: workflows/wdl/w1/singleDescriptorWithInput.wdl
      testParameterFiles:
        - /workflows/wdl/w1/test.json
This will fail (note the relative paths to each primary descr
